on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'  # Update to the appropriate Java version
          distribution: 'temurin'

      - name: Set up PostgreSQL
        uses: docker://postgres:latest
        with:
          env:
            POSTGRES_USER: power
            POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            POSTGRES_DB: merchandise
          ports:
            - 5432:5432
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      - name: Build and Test
        run: |
          # Set environment variables for the Spring Boot application
          export SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/merchandise
          export SPRING_DATASOURCE_USERNAME=power
          export SPRING_DATASOURCE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}
          
          # Build and test the application using Maven
          ./mvnw clean install

          # Your further steps, e.g., running the Spring Boot app

      # Continue with deployment or other steps as needed
